version: "3.7"

services:
  etcd:
    hostname: etcd
    image: quay.io/coreos/etcd:v3.5.1
    labels:
      - com.shardman.role=etcd
    command:
      - '/usr/local/bin/etcd'
      - '--name=etcd'
      - '--initial-advertise-peer-urls=http://etcd:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--advertise-client-urls=http://etcd:2379'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--initial-cluster=etcd=http://etcd:2380'
  shard:
    labels:
      - com.shardman.role=shard
    image: quay.io/kakoka/sdm-systemd:b04
    cap_add:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - $PWD/conf:/etc/shardman:ro
    environment: &ETCD
      CLUSTER_NAME: "cluster0"
      SDM_CLUSTER_NAME: "cluster0"
      SDM_LOG_LEVEL: "info"
      SDM_STORE_ENDPOINTS: "http://etcd:2379"