version: "3.7"

services:

  etcd:
    hostname: etcd
    image: quay.io/coreos/etcd:v3.5.6
    platform: linux/amd64
    labels:
      com.shardman.role: etcd
    volumes:
      - /tmp/etcd:/var/lib/etcd:rw
    command:
      - '/usr/local/bin/etcd'
      - '--name=etcd'
      - '--initial-advertise-peer-urls=http://etcd:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--advertise-client-urls=http://etcd:2379'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--initial-cluster=etcd=http://etcd:2380'

  shard:
    &shard
    image: quay.io/kakoka/shardman:14.7.1
    platform: linux/amd64
    labels:
      &labels
      com.shardman.role: shard
      com.shardman.main: true
    cap_add: [ "SYS_ADMIN" ]
    tmpfs:
      &tmpfs
      - /run
      - /run/lock
    volumes:
      &volumes
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - $PWD/conf/spec.json:/etc/shardman/spec.json:ro
      - $PWD/conf/shardmand-cluster0.env:/etc/shardman/shardmand-cluster0.env:ro
    environment:
      &ETCD
      CLUSTER_NAME: "cluster0"
      SDM_CLUSTER_NAME: "cluster0"
      SDM_LOG_LEVEL: "info"
      SDM_STORE_ENDPOINTS: "http://etcd:2379"
    expose:
      - 5432
    ports:
      &ports
      - 5432:5432

  shards:
    <<: *shard
    labels:
      com.shardman.role: shard
    ports: []
